# Generated by Django 5.2.13 on 2026-04-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EscuelaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Alumnos',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Profesores',
        ),
    ]
