# Generated by Django 5.2.13 on 2026-04-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscuelaApp', '0002_rename_alumno_alumnos_rename_profesor_profesores'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='fotoPerfilUrl',
            field=models.URLField(default='http://127.0.0.1:8000/foto.png'),
            preserve_default=False,
        ),
    ]
