# Generated by Django 5.2.13 on 2026-04-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscuelaApp', '0003_alumnos_fotoperfilurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='password',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
