# Generated by Django 5.2.13 on 2026-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscuelaApp', '0004_alumnos_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='fotoPerfilUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
