# Generated by Django 5.2.13 on 2026-05-10 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscuelaApp', '0005_alter_alumnos_fotoperfilurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.BigIntegerField()),
                ('alumnoId', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('sessionString', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'sesiones_alumnos',
            },
        ),
    ]
